networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  kafka-data:
  jenkins-data:
  maven-repo:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  sonarqube-db-data:

services:

  # ---------------- ZOOKEEPER ----------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    networks: [app-network]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: unless-stopped

  # ---------------- KAFKA ----------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    networks: [app-network]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  # ---------------- POSTGRES ----------------
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    networks: [app-network]
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  # ---------------- APP ----------------
  order-payment-app:
    image: raishyam/order-payment-system:latest
    container_name: order-payment-app
    networks: [app-network]
    depends_on:
      - postgres
      - kafka
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: unless-stopped

  # ---------------- JENKINS ----------------
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    networks: [app-network]
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - maven-repo:/root/.m2
    user: root
    restart: unless-stopped

  # ---------------- SONAR DB ----------------
  sonarqube-db:
    image: postgres:15-alpine
    container_name: sonarqube-db
    networks: [app-network]
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    restart: unless-stopped

  # ---------------- SONARQUBE ----------------
  sonarqube:
    image: sonarqube:10-community
    container_name: sonarqube
    networks: [app-network]
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_WEB_JAVAOPTS: "-Xmx512m"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    restart: unless-stopped